-- MySQL Script generated by MySQL Workbench
-- Fri 15 Nov 2019 12:50:43 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema java_coffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema java_coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `java_coffee` DEFAULT CHARACTER SET utf8 ;
USE `java_coffee` ;

-- -----------------------------------------------------
-- Table `java_coffee`.`core_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`core_student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `student_number` VARCHAR(64) NOT NULL,
  `student_name` VARCHAR(64) NULL,
  `student_sex` VARCHAR(8) NULL,
  `student_year` INT NULL DEFAULT 1900,
  `student_class` VARCHAR(64) NULL,
  `student_school` VARCHAR(64) NULL,
  `student_email` VARCHAR(64) NULL,
  `student_password` VARCHAR(32) NULL DEFAULT '123456789',
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `id_UNIQUE` (`student_id` ASC),
  UNIQUE INDEX `student_number_UNIQUE` (`student_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`core_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`core_teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `teacher_number` VARCHAR(64) NOT NULL,
  `teacher_name` VARCHAR(64) NULL,
  `teacher_sex` VARCHAR(8) NULL,
  `teacher_school` VARCHAR(64) NULL,
  `techer_title` VARCHAR(64) NULL,
  `teacher_email` VARCHAR(64) NULL,
  `teacher_password` VARCHAR(64) NULL DEFAULT '123456789',
  PRIMARY KEY (`teacher_id`),
  UNIQUE INDEX `teacher_number_UNIQUE` (`teacher_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`core_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`core_course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_number` VARCHAR(64) NOT NULL,
  `course_name` VARCHAR(64) NULL,
  `course_school` VARCHAR(64) NULL,
  `course_year` VARCHAR(8) NULL,
  `course_weeks` VARCHAR(64) NULL,
  `course_credit` FLOAT NULL,
  `course_class` INT NULL,
  `course_type` VARCHAR(64) NULL,
  `teacher_id` INT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_core_course_teacher_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_core_course_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `java_coffee`.`core_teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`core_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`core_file` (
  `file_type` VARCHAR(16) NULL,
  `file_name` VARCHAR(256) NULL,
  `file_path` VARCHAR(512) NOT NULL,
  `file_date` TIMESTAMP NULL,
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_core_file_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_core_file_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `java_coffee`.`core_course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`core_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`core_notice` (
  `notice_id` INT NOT NULL AUTO_INCREMENT,
  `notice_date` TIMESTAMP NULL,
  `notice_level` INT NULL,
  `notice_content` LONGTEXT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`notice_id`),
  INDEX `fk_core_notice_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_core_notice_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `java_coffee`.`core_course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`sys_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`sys_admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(64) NULL,
  `admin_password` VARCHAR(64) NULL,
  `admin_email` VARCHAR(64) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java_coffee`.`student_has_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `java_coffee`.`student_has_course` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `course_id`),
  INDEX `fk_student_has_course_core_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_student_has_course_core_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `java_coffee`.`core_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_core_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `java_coffee`.`core_course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
